### ISSUE TITLE
CreateToolhelp32Snapshot issue when building

### ISSUE THREAD

**Issue by TurBoss** [opalmer/pywincffi#100]
Hi

I have added the definition to de headers and created a function in the process.py
but when i try to build i get this error

http://dpaste.com/2XV5JF4

any ideas 
thx!

**Comment by TurBoss** [comment]
here ii an extract of the process.py file not doc yet (I know)
http://dpaste.com/1YEGNVF

**Comment by TurBoss** [comment]
I found a missing ")" 

but continues droping the compile error

here is my fork https://github.com/TurBoss/pywincffi/

**Comment by opalmer** [comment]
Sorry for the delay!

Looks like you're missing an `#include` statement in pywincffi/core/cdefs/sources/main.c.  Here's a branch I made based off of yours which seems to compile for me:

https://github.com/opalmer/pywincffi/compare/debug_CreateToolhelp32Snapshot

So try adding that include statement in your branch and let me know if it works.  When you're ready I'll be happy to do a code review if you open up a PR (I assume that's the direction you're heading?).

**Comment by TurBoss** [comment]
ok it works but where is documented the requirement? ok i found it :D
sry i'm newby :P

i'll document the function and mke a PR soon
