### ISSUE TITLE
CreateProcess() passes lpEnvironment which is a dict, needs to be a block of name=value

### ISSUE THREAD

**Issue by rodrigc** [opalmer/pywincffi#134]
See:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425(v=vs.85).aspx

and

https://github.com/opalmer/pywincffi/blob/master/pywincffi/kernel32/process.py#L425

Twisted currently passes in an lpEnvironment which is a dict, similar to what os.environ() gives you.

However, `CreateProcess` needs to accept a block of null terminated strings, of format `name=value`.

It looks like win32api does this conversion under the covers, but pywincffi does not.
This leads to errors with pywincffi in Twisted:  *The parameter is incorrect*

**Comment by rodrigc** [comment]
If you look here:
https://github.com/Travis-Sun/pywin32/blob/master/win32/src/win32process.i#L639

you see that **CreateEnvironmentString** is called on the environment pointer.

The implementation of **CreateEnvironmentString** is here: https://github.com/Travis-Sun/pywin32/blob/master/win32/src/win32process.i#L485

pywincffi needs to do something similar.

**Comment by opalmer** [comment]
pywincffi already does something similar, Inside of `CreateProcess()` currently there's:

```python
    if lpEnvironment is not None:
        lpEnvironment = _text_to_wchar(_environment_to_string(lpEnvironment))
    else:
        lpEnvironment = ffi.NULL
```

And `_environment_to_string()` does:

```python
def _environment_to_string(environment):
    """
    This function is used internally by :func:`CreateProcess` to convert
    the input to ``lpEnvironment`` to a string which the underlying C API
    call will understand.

    >>> from pywincffi.kernel32.process import _environment_to_string
    >>> _environment_to_string({"A": "a", "B": "b"})
    'A=a\x00B=b'

    :param environment:
        A dictionary or dictionary like object to convert to a string.

    :raises InputError:
        Raised if we cannot convert ``environment`` to a string.  This can
        happen if:

            * ``environment`` is not a dictionary like object.
            * Not all keys and values in the environment are strings (
              str in Python 3.x, unicode in Python 2.x)
            * One or more of the keys contains the `=` symbol.
    """
```

There's also a test specifically for this too that launches a Python process using CreateProcess() with unicode environment variables, uses and data from some of those variables to disk and then reads them back in in the main process:

https://github.com/opalmer/pywincffi/blob/master/tests/test_kernel32/test_process.py#L591

Is there something I'm missing here or could Twisted be doing something to the arguments before they reach CreateProcess that could be causing issues?

**Comment by rodrigc** [comment]
Twisted is not doing anything special.  This code is definitely not working.

During the inspection of the code, one thing I would say is that the unicode vs. str
handling could be tightened up.  I think that is part of the problem here.

**Comment by rodrigc** [comment]
One thing I would recommend is to use str.format() instead of "%s" style formatting.
That leads to less gotchas with unicode on Python 2:

https://mail.python.org/pipermail/python-dev/2017-May/147949.html

**Comment by opalmer** [comment]
Could you do a dump of the exact inputs being sent to `win32process.CreateProcess` and pywincffi's `CreateProcess()` by Twisted please so I can compare the two? 

Most of the code in pywincffi just checks to make sure it's a `six.text_type` then does little conversion after that since going from 'string' to a C type can sometimes end up being a mess if you're not careful. However you may be right about `%s` though which is why I'd like to have some data to test against.
