### ISSUE TITLE
Which branch to PR against?

### ISSUE THREAD

**Issue by exvito** [opalmer/pywincffi#65]
Hello @opalmer 

Following up our discussion over at Twisted's mailing list I plan on issuing two PRs:
- One for the handle related APIs: **GetHandleInformation** and **SetHandleInformation**.
- Another for the low-level APIs: **NtQuerySystemInformation** and **NtQueryObject**.

I'll start with the handle related one, simpler from an API standpoint. This will allow me (with your guidance) to build something that fits nicely into the existing code base.

Once you find that PR is good enough for merging, I'll move on to the other one. Without having given it much thought and without being familiar with pywincffi yet, one of the challenges we'll face is a matter of C vs Python semantics in the "function signatures": the NtQuery\* APIs return information via memory buffers that are passed in as C pointers -- not sure how to translate that into a nice and clear Pythonic approach / "function signature". We'll get there.

Before I get started, I'd just like you to please recommend the branch against which you'd like the first PR issued.

Of course, I welcome any advice and preliminary guidance you feel may be useful.

Cheers.

**Comment by opalmer** [comment]
Hey @exvito, welcome!

Starting with GetHandleInformation/SetHandleInformation sounds like the right place to start to me and I'd recommend basing your work off the master branch.  Any other branches are works in progress so I wouldn't recommend basing something off of those usually. Generally speaking I always try to keep the master branch release ready so it's usually the best place to start working from.  I do plan on making a release soon but that shouldn't have any impact on the work you're doing.

As for preliminary advice and guidance, I'll start by suggesting that you read over [README.rst](https://github.com/opalmer/pywincffi/blob/master/README.rst) at the root of the repository.  I've tried to capture most of the development practices, project goals, as well as some information about testing and documentation there.  I also setup a [google group](https://groups.google.com/forum/#!forum/pywincffi) too a while back, which I'm planning to add this to the readme soon, so feel free to post there if you have additional questions or need to start a longer discussion. 

[Original discussion on Twisted mailing list ](https://twistedmatrix.com/pipermail/twisted-python/2016-April/030255.html)\- For our own reference as well as anyone else who looks in the future.

**Comment by exvito** [comment]
Closing. Created PR #66.
